Repository storybookjs/jest, pull requests merged in 2022-02, with the labels that each got.

#11 chore: add auto-release process
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/release.yml
  .gitignore
  README.md
  package.json
Labels: skip-release

#9 Fix #8: Generated type of expect
  src/index.ts
Labels: patch

#12 feat: add testing-library expect matchers
  package.json
  src/index.ts
  src/typings.d.ts
Labels: patch, release

#13 deps: upgrade @storybook/instrumenter
  package.json
Labels: patch, release

#14 deps: use latest storybook instrumenter
  package.json
Labels: patch, release
