Repository storybookjs/jest, pull requests merged in 2023-08, with the labels that each got.

#33 docs: update link
  README.md
Labels: documentation, skip-release

#34 Fix: Make sure that expect matches the runtime type when instrumented
  package.json
  src/index.ts
Labels: minor

#36 Release/0.2.0
  .github/ISSUE_TEMPLATE/bug-report-🐞.md
  .github/workflows/linear-export.yml
  .github/workflows/release.yml
  CODEOWNERS
  README.md
  package.json
  src/index.ts
  tsconfig.cjs.json
  tsconfig.esm.json
  tsconfig.json
  tsup.config.ts
Labels: minor

#37 Specify triple slash reference in banner
  tsup.config.ts
Labels: bug, patch

#38 Release 0.2.1
  tsup.config.ts
Labels: patch

#41 Fix version in package.json, support yarn 3
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/release.yml
  .gitignore
  .yarnrc.yml
  package.json
  yarn.lock
Labels: skip-release

#43 Release 0.2.2
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/release.yml
  .gitignore
  .yarnrc.yml
  README.md
  package.json
  src/index.ts
  tsup.config.ts
  yarn.lock
Labels: patch
