Repository storybookjs/jest, pull requests merged in 2023-04, with the labels that each got.

#24 Release 0.1.0
  package.json
Labels: minor

#25 Add more explanation to the types FAQ
  README.md
Labels: documentation, skip-release

#26 Change build scripts to use tsup instead of tsc
  package.json
  tsconfig.cjs.json
  tsconfig.esm.json
  tsconfig.json
Labels: patch

#27 Prebundle @storybook/instrumenter package
  .github/workflows/linear-export.yml
  .github/workflows/release.yml
  package.json
  tsup.config.ts
Labels: minor
